### ISSUE TITLE
Flask Torrent API giving 2 API_KEY's

### ISSUE THREAD

**Issue by BullShark** [BullShark/JRobo#13]
```
(venv) root@odin:/var/www/expectusafterlun.ch/public_html/FlaskApp# python torrent.py 
**[*] API_KEY: vkOyiz2wGi08qWSrIt24UpajpYdOFH3w** 
* Serving Flask app 'torrent' (lazy loading) 
* Environment: production WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead. 
* Debug mode: on 
* Running on all addresses. WARNING: This is a development server. Do not use it in a production deployment. 
* Running on http://152.89.107.76:5000/ (Press CTRL+C to quit) 
* Restarting with stat **[*] API_KEY: 9Nn8Vp5djUgcoEVyiPENasPOHfLFsQeD** 
* Debugger is active! * Debugger PIN: 124-170-670
```

**Comment by thatsn0tmysite** [comment]
Can't replicate. Are you sure you didn't save the file you were editing? When in development mode Flask reloads all files and therefore restarts the script, causing it to return the second API.

Should be fixed by setting `app.config["DEBUG"]=False` in [torrents.py](https://github.com/BullShark/JRobo/blob/master/src/main/java/FlaskPython/torrent.py)

**Comment by BullShark** [comment]
I don't know Flask that well. I am running in development mode. I don't know how to run in non-development mode.

![image](https://user-images.githubusercontent.com/1526595/141082441-5b6b035d-3ddd-4b06-930e-b80185a4e488.png)

**Comment by BullShark** [comment]
Setting debug = false resolved it.
